# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5385a31f5b5ada93b55c96203420bc42d57132e28b03651aa8f8888968b250a7414b045ea961a3c8bca3fcbe55409abd5610694ba8b0c465da21863e026132b1

test:
  secret_key_base: bb243fa4e24140a12f28343f8ae726d255576d24a0c2b15960b2f1174cfa00baa56804691a212806ee610a9c410fc2c971ef9eb896b0a3140107d1113ce37299

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
